import { Command } from "commander";
import ora from "ora";
import { join } from "node:path";
import { readFile } from "node:fs/promises";

import { loadConfig } from "../config/config-loader.js";
import {
  findProjectRoot,
  pathExists,
  readJsonFile,
  writeFileWithDir,
} from "../utils/fs.js";
import { log } from "../utils/logger.js";
import { renderTemplate } from "../utils/template.js";
import { frameworkRange, withVersions } from "../versions.js";
import {
  nativeAppBabelConfig,
  nativeAppBootTs,
  nativeAppGitignore,
  nativeAppGlobalCss,
  nativeAppI18nTs,
  nativeAppIndexScreen,
  nativeAppJson,
  nativeAppMetroConfig,
  nativeAppNativewindEnv,
  nativeAppPackageJson,
  nativeAppReadme,
  nativeAppRootLayout,
  nativeAppTailwindConfig,
  nativeAppTsconfigJson,
} from "../templates/native-app/index.js";

/** Built-in translations for the generated common namespace. */
const COMMON_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appName: "{{appName}}",
    welcomeTitle: "Welcome",
    welcomeDescription: "This app was generated by simplix add-app --native.",
  },
  ko: {
    appName: "{{appName}}",
    welcomeTitle: "환영합니다",
    welcomeDescription: "simplix add-app --native로 생성된 앱입니다.",
  },
  ja: {
    appName: "{{appName}}",
    welcomeTitle: "ようこそ",
    welcomeDescription: "simplix add-app --native で生成されたアプリです。",
  },
};

const NATIVE_HOIST_PATTERNS = [
  "public-hoist-pattern[]=@simplix-react-native/*",
  "public-hoist-pattern[]=@simplix-react-native-ext/*",
];

function commonLocaleJson(appName: string, locale: string): string {
  const entries = COMMON_TRANSLATIONS[locale] ?? COMMON_TRANSLATIONS.en;
  const resolved = Object.fromEntries(
    Object.entries(entries).map(([key, value]) => [
      key,
      value.replace("{{appName}}", appName),
    ]),
  );
  return `${JSON.stringify(resolved, null, 2)}\n`;
}

async function ensureNativeHoistPatterns(rootDir: string): Promise<void> {
  const npmrcPath = join(rootDir, ".npmrc");
  let content = "";
  if (await pathExists(npmrcPath)) {
    content = await readFile(npmrcPath, "utf-8");
  }
  const missing = NATIVE_HOIST_PATTERNS.filter((line) => !content.includes(line));
  if (missing.length === 0) return;
  const next = `${content.trimEnd()}\n${missing.join("\n")}\n`.replace(/^\n/, "");
  await writeFileWithDir(npmrcPath, next);
}

export const addAppCommand = new Command("add-app")
  .description("Add a new app shell to the workspace")
  .argument("<name>", "App name (e.g., visitor-kiosk)")
  .option("--native", "Generate an Expo (React Native) app with expo-router")
  .option("-y, --yes", "Accept all defaults (non-interactive)")
  .action(async (name: string, flags: Record<string, unknown>) => {
    if (!flags.native) {
      log.error(
        "add-app currently generates native apps only. Use --native, or `simplix init` for the web app shell.",
      );
      process.exit(1);
    }

    const rootDir = await findProjectRoot(process.cwd());
    const rootPkg = await readJsonFile<{ name: string }>(
      join(rootDir, "package.json"),
    ).catch(() => null);

    if (!rootPkg) {
      log.error(
        "No package.json found. Run this command from a simplix project root.",
      );
      process.exit(1);
    }

    const scopeMatch = rootPkg.name.match(/^(@[^/]+)\//);
    const scope = scopeMatch ? scopeMatch[1] : "";

    const config = await loadConfig(rootDir);
    const locales = config.i18n?.locales ?? ["en", "ko", "ja"];
    const defaultLocale = config.i18n?.defaultLocale ?? locales[0] ?? "en";

    const targetDir = join(rootDir, "apps", name);
    if (await pathExists(targetDir)) {
      log.error(`App "${name}" already exists.`);
      process.exit(1);
    }

    const spinner = ora(`Creating native app: ${name}`).start();

    try {
      const ctx = withVersions({
        appName: name,
        scope,
        locales,
        defaultLocale,
        nativeFw: frameworkRange("@simplix-react/cli"),
        projectName: rootPkg.name.replace(/^@[^/]+\//, ""),
      });

      const files: Record<string, string> = {
        "package.json": renderTemplate(nativeAppPackageJson, ctx),
        "app.json": renderTemplate(nativeAppJson, ctx),
        "babel.config.js": renderTemplate(nativeAppBabelConfig, ctx),
        "metro.config.js": renderTemplate(nativeAppMetroConfig, ctx),
        "tailwind.config.js": renderTemplate(nativeAppTailwindConfig, ctx),
        "global.css": renderTemplate(nativeAppGlobalCss, ctx),
        "tsconfig.json": renderTemplate(nativeAppTsconfigJson, ctx),
        "nativewind-env.d.ts": renderTemplate(nativeAppNativewindEnv, ctx),
        ".gitignore": renderTemplate(nativeAppGitignore, ctx),
        "README.md": renderTemplate(nativeAppReadme, ctx),
        "app/_layout.tsx": renderTemplate(nativeAppRootLayout, ctx),
        "app/index.tsx": renderTemplate(nativeAppIndexScreen, ctx),
        "src/app/boot.ts": renderTemplate(nativeAppBootTs, ctx),
        "src/app/i18n.ts": renderTemplate(nativeAppI18nTs, ctx),
      };

      for (const locale of locales) {
        files[`src/locales/common/${locale}.json`] = commonLocaleJson(name, locale);
      }

      for (const [relativePath, content] of Object.entries(files)) {
        await writeFileWithDir(join(targetDir, relativePath), content);
      }

      await ensureNativeHoistPatterns(rootDir);

      spinner.succeed(`Native app created: apps/${name}`);
      log.info("");
      log.info("Next steps:");
      log.info("  1. pnpm install");
      log.info(`  2. pnpm --filter ${scope ? `${scope}/` : ""}${name} start`);
      log.info("  3. Set EXPO_PUBLIC_API_URL for device/emulator API access");
      log.info(
        "  4. Generate entity screens: simplix scaffold <entity> --native --module <module> --app " +
          name,
      );
    } catch (error) {
      spinner.fail("Failed to create native app");
      log.error(error instanceof Error ? error.message : String(error));
      process.exit(1);
    }
  });
