/**
 * The application's own 13 domains, copied from its `simplix.config.ts`. `data-io` is a quoted
 * key there; a reader that only accepts bare identifiers drops it and its 44 operations.
 */
export const smartSafetyDomains: Record<string, string[]> = {
  "dashboard": [
    "dashboard.Dashboard",
  ],
  "space": [
    "space.Site",
    "space.SiteConfiguration",
    "space.SiteClosure",
    "space.Area",
    "space.Drawing",
    "space.ShiftConfig",
    "space.Equipment",
    "space.EquipmentDisposal",
    "space.NumberedDocumentKind",
  ],
  "site": [
    "site.AreaZone",
    "site.SafetyZonePolicy",
    "site.SiteOnboarding",
    "site.EquipmentInspection",
    "site.EquipmentJudgement",
    "site.LinearAsset",
    "site.WorkPoint",
  ],
  "worker": [
    "party.roster.Worker",
    "party.roster.WorkerCensus",
    "party.roster.WorkerInvitation",
    "party.roster.WorkerExit",
    "party.roster.WorkerProtectedFields",
  ],
  "org": [
    "org.Organization",
    "org.OrgType",
  ],
  "regulation": [
    "regulation.RegulationPack",
    "regulation.LawPackInstallation",
    "regulation.LawPackCensus",
    "regulation.RegulationRegisterEntry",
    "regulation.RegulationDuty",
    "regulation.LawRegisterCensus",
    "regulation.LawScreenMap",
    "regulation.ComplianceCheck",
    "regulation.ComplianceRun",
    "regulation.ObligationApplicability",
    "regulation.ObligationAssessment",
    "regulation.ObligationCensus",
    "regulation.PolicyParameter",
    "regulation.PolicyValueResolution",
    "regulation.PolicyValueCensus",
    "regulation.PolicyWarning",
    "regulation.RetentionPolicy",
    "regulation.RetentionPolicyCensus",
    "regulation.PreAssignmentGate",
    "regulation.GatePolicyCensus",
    "regulation.ContentLanguage",
    "regulation.ContentLanguageCensus",
  ],
  "auth": [
    "common.auth.RoleScopeGrant",
    "common.auth.SecurityPolicy",
    "common.auth.HealthSeparationSetting",
    "common.auth.IdentityProviderConfig",
    "common.auth.AuthSession",
    "public.auth.SignInOption",
    "common.auth.ScopeAxis",
  ],
  "audit": [
    "audit.AuditLog",
    "audit.MasterDataHistory",
    "common.main.audit.AuditEvent",
  ],
  "notification": [
    "notification.Notification",
    "notification.NotificationCentre",
    "notification.NotificationHistoryCensus",
    "notification.NotificationRule",
    "notification.NotificationRuleCensus",
    "notification.NotificationDelivery",
    "notification.MessageChannel",
    "notification.MessageChannelCensus",
    "notification.MessageTemplate",
    "notification.MessageTemplateCensus",
    "notification.MessagePreview",
    "notification.MailConfig",
    "notification.MailConfigCensus",
    "notification.MailTestLog",
    "notification.Notice",
    "notification.NoticeCensus",
    "notification.EmergencyContact",
    "notification.EmergencyContactCensus",
    "notification.OnCallRoster",
    "notification.OnCallRosterCensus",
    "notification.DutyRoster",
  ],
  "approval": [
    "approval.ApprovalInbox",
    "approval.ApprovalRequest",
    "approval.ApprovalLineTemplate",
    "approval.ApprovalLineCensus",
    "approval.ApprovalDelegation",
    "approval.ApprovalDelegationCensus",
    "approval.DelegationPolicy",
    "approval.DelegationPolicyCensus",
  ],
  "data-io": [
    "data-io.ImportJob",
    "data-io.ImportCensus",
    "data-io.ImportRun",
    "data-io.BulkOperation",
    "data-io.BulkCensus",
    "data-io.BulkReversal",
    "data-io.DuplicateCandidate",
    "data-io.DuplicateCensus",
    "data-io.DuplicateMerge",
    "data-io.ExportLedger",
    "data-io.ExportCensus",
  ],
  "system": [
    "common.main.system.SystemSetting",
    "common.main.system.HolidayCalendar",
    "common.main.system.Holiday",
    "system.SiteSettings",
    "system.NotificationSettings",
    "system.ExportJob",
    "system.ExportDownload",
    "system.MailCheck",
    "system.ConsoleNotification",
    "system.NoticeDismissal",
    "common.email.EmailLog",
    "public.system.DeploymentBootstrap",
    "public.system.InstallationSetup",
  ],
  "user": [
    "user.admin.UserAccount",
    "user.admin.UserAvatar",
    "user.admin.UserRole",
    "user.admin.UserSecurityProfile",
    "user.admin.UserNote",
    "user.admin.JobPosition",
    "user.admin.StatutoryAppointmentKind",
    "user.admin.UserAccessLog",
    "user.admin.UserAccountCensus",
    "common.user.CurrentUser",
    "common.user.CurrentUserSession",
    "common.user.CurrentUserAvatar",
    "common.user.CurrentUserPermissions",
    "common.user.MfaChallenge",
    "common.auth.AuthPermission",
    "common.auth.AuthRolePermission",
    "public.user.OperatorLink",
    "public.user.Avatar",
    "public.user.AvatarThumbnail",
    "public.user.Permissions",
  ],
};
