import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, rm, readFile, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), "i18n-codegen-test-"));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

// Mirror the private helpers from i18n-codegen.ts for testing

function flattenKeys(obj: Record<string, unknown>, prefix = ""): string[] {
  const keys: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      keys.push(...flattenKeys(value as Record<string, unknown>, fullKey));
    } else {
      keys.push(fullKey);
    }
  }
  return keys;
}

function toTypeName(dirName: string): string {
  return dirName
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

describe("flattenKeys", () => {
  it("flattens simple object", () => {
    expect(flattenKeys({ a: "1", b: "2" })).toEqual(["a", "b"]);
  });

  it("flattens nested object with dot notation", () => {
    expect(flattenKeys({ user: { name: "Alice", age: 30 } })).toEqual(["user.name", "user.age"]);
  });

  it("flattens deeply nested object", () => {
    expect(flattenKeys({ a: { b: { c: "deep" } } })).toEqual(["a.b.c"]);
  });

  it("returns empty for empty object", () => {
    expect(flattenKeys({})).toEqual([]);
  });

  it("handles mixed nesting", () => {
    const keys = flattenKeys({
      greeting: "Hello",
      user: { name: "Alice" },
    });
    expect(keys).toEqual(["greeting", "user.name"]);
  });
});

describe("toTypeName", () => {
  it("converts kebab-case to PascalCase", () => {
    expect(toTypeName("features")).toBe("Features");
    expect(toTypeName("my-component")).toBe("MyComponent");
  });

  it("handles single word", () => {
    expect(toTypeName("widgets")).toBe("Widgets");
  });

  it("handles multi-segment", () => {
    expect(toTypeName("my-awesome-module")).toBe("MyAwesomeModule");
  });
});

describe("keys.d.ts generation (integration)", () => {
  it("generates keys.d.ts from en.json", async () => {
    const modulesDir = join(tempDir, "modules/test-mod/src/locales/features");
    await mkdir(modulesDir, { recursive: true });
    await writeFile(join(modulesDir, "en.json"), JSON.stringify({
      greeting: "Hello",
      user: { name: "Name", email: "Email" },
    }));

    // Simulate what generateKeysFile would produce
    const content = await readFile(join(modulesDir, "en.json"), "utf-8");
    const json = JSON.parse(content) as Record<string, unknown>;
    const keys = flattenKeys(json);
    const namespace = toTypeName("features");
    const keysType = `${namespace}Keys`;

    const lines = [
      "// Auto-generated by simplix i18n-codegen",
      "// Do not edit manually",
      "",
      `export type ${keysType} =`,
      ...keys.map((key, i) => {
        const suffix = i === keys.length - 1 ? ";" : "";
        return `  | "${key}"${suffix}`;
      }),
      "",
    ];

    const output = lines.join("\n");
    expect(output).toContain("FeaturesKeys");
    expect(output).toContain('"greeting"');
    expect(output).toContain('"user.name"');
    expect(output).toContain('"user.email"');
  });
});
