import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, writeFile, mkdir, rm, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import type { ValidationResult } from "../commands/validate.js";

// Inject globals that tsup normally provides at build time
(globalThis as Record<string, unknown>).__DEP_VERSIONS__ = {
  typescript: "^7.0.2",
  "typescript-expo": "~5.9.3",
};

// Import after globals are set
const { validateRootRules, validateTsconfigBaseUrl, validateExpoTypescript } = await import(
  "../validators/root-rules.js"
);

let tempDir: string;

function createResult(path: string): ValidationResult {
  return { path, errors: [], warnings: [], passes: [] };
}

function autoFixes(result: ValidationResult): string[] {
  return result.passes.filter((p) => p.startsWith("Auto-fixed"));
}

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), "simplix-root-rules-"));
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

// The 0.3.10 project template, as a project generated by it carries the file.
const oldTurboJson = `{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env*"],
      "outputs": ["dist/**"]
    },
    "dev": {
      "dependsOn": ["^build"],
      "cache": false
    },
    "dev:app": {
      "dependsOn": ["^build"],
      "cache": false,
      "persistent": true
    },
    "typecheck": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", "tsconfig.json"]
    },
    "lint": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$"]
    },
    "test": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$"],
      "outputs": ["coverage/**"]
    },
    "clean": {
      "cache": false
    }
  }
}
`;

const oldScripts: Record<string, string> = {
  build: "turbo run clean && turbo run build --force --concurrency=4",
  dev: "turbo run clean && turbo run build --concurrency=4 && turbo watch dev:app",
  "dev:b": "turbo watch dev:app --filter=@a/b",
  "build:x": "turbo run build --force --concurrency=4 --filter=@a/x",
  "dev:kiosk": "pnpm --filter @a/kiosk start",
  typecheck: "turbo run typecheck",
};

function rootPackageJson(scripts: Record<string, string>): string {
  const lines = Object.entries(scripts).map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)}`);
  return `{
  "name": "@a/monorepo",
  "private": true,
  "scripts": {
${lines.join(",\n")}
  },
  "devDependencies": {
    "typescript": "catalog:"
  }
}
`;
}

const oldWorkspace = `packages:
  - packages/*
  - apps/*

catalog:
  tsup: ^8.5.1
  typescript: ^5.9.3
  vite: ^8.0.0

onlyBuiltDependencies:
  - esbuild
`;

async function writeOldRoot(scripts: Record<string, string> = oldScripts): Promise<void> {
  await writeFile(join(tempDir, "turbo.json"), oldTurboJson);
  await writeFile(join(tempDir, "package.json"), rootPackageJson(scripts));
  await writeFile(join(tempDir, "pnpm-workspace.yaml"), oldWorkspace);
}

describe("validateRootRules: turbo.json", () => {
  it("warns without --fix and leaves the file alone", async () => {
    await writeOldRoot();
    const result = createResult(".");
    await validateRootRules(tempDir, result);

    expect(result.warnings.some((w) => w.includes("turbo.json"))).toBe(true);
    expect(await readFile(join(tempDir, "turbo.json"), "utf-8")).toBe(oldTurboJson);
  });

  it("drops builds from dev:app and lint, chains typecheck, and caps concurrency", async () => {
    await writeOldRoot();
    await validateRootRules(tempDir, createResult("."), { fix: true });

    const text = await readFile(join(tempDir, "turbo.json"), "utf-8");
    const turbo = JSON.parse(text);
    expect(turbo.concurrency).toBe("4");
    expect(turbo.tasks["dev:app"].dependsOn).toEqual([]);
    expect(turbo.tasks.lint.dependsOn).toEqual([]);
    expect(turbo.tasks.typecheck.dependsOn).toEqual(["^typecheck"]);
    expect(turbo.tasks.test.dependsOn).toEqual(["^build"]);
    expect(turbo.tasks.build.dependsOn).toEqual(["^build"]);
    expect(text).toBe(
      oldTurboJson
        .replace('"$schema": "https://turbo.build/schema.json",\n', '"$schema": "https://turbo.build/schema.json",\n  "concurrency": "4",\n')
        .replace('"dev:app": {\n      "dependsOn": ["^build"]', '"dev:app": {\n      "dependsOn": []')
        .replace('"typecheck": {\n      "dependsOn": ["^build"]', '"typecheck": {\n      "dependsOn": ["^typecheck"]')
        .replace('"lint": {\n      "dependsOn": ["^build"]', '"lint": {\n      "dependsOn": []'),
    );
  });
});

describe("validateRootRules: scripts", () => {
  it("rewrites the known dev and build forms and keeps the rest", async () => {
    await writeOldRoot();
    await validateRootRules(tempDir, createResult("."), { fix: true });

    const text = await readFile(join(tempDir, "package.json"), "utf-8");
    expect(JSON.parse(text).scripts).toEqual({
      build: "turbo run clean && turbo run typecheck build --force --concurrency=4",
      dev: "turbo run dev:app",
      "dev:b": "turbo run dev:app --filter=@a/b",
      "build:x": "turbo run typecheck build --force --concurrency=4 --filter=@a/x...",
      "dev:kiosk": "pnpm --filter @a/kiosk start",
      typecheck: "turbo run typecheck",
    });
    expect(text).toContain('"devDependencies": {\n    "typescript": "catalog:"\n  }');
  });

  it("warns about a turbo watch it does not know and leaves it", async () => {
    await writeOldRoot({ w: "turbo watch something" });
    const result = createResult(".");
    await validateRootRules(tempDir, result, { fix: true });

    expect(result.warnings.some((w) => w.includes('"w"'))).toBe(true);
    expect(JSON.parse(await readFile(join(tempDir, "package.json"), "utf-8")).scripts.w).toBe(
      "turbo watch something",
    );
  });

  it("leaves a script that runs a plain app without a warning", async () => {
    await writeOldRoot();
    const result = createResult(".");
    await validateRootRules(tempDir, result, { fix: true });

    expect(result.warnings.some((w) => w.includes("dev:kiosk"))).toBe(false);
  });

  it("warns about a script that starts or exports an Expo app", async () => {
    await writeOldRoot();
    await mkdir(join(tempDir, "apps/kiosk"), { recursive: true });
    await writeFile(
      join(tempDir, "apps/kiosk/package.json"),
      JSON.stringify({
        name: "@a/kiosk",
        scripts: { start: "expo start" },
        dependencies: { expo: "^54.0.0" },
      }),
    );
    const result = createResult(".");
    await validateRootRules(tempDir, result, { fix: true });

    expect(result.warnings.some((w) => w.includes('"dev:kiosk"'))).toBe(true);
    expect(JSON.parse(await readFile(join(tempDir, "package.json"), "utf-8")).scripts["dev:kiosk"]).toBe(
      "pnpm --filter @a/kiosk start",
    );
  });
});

describe("validateRootRules: catalog TypeScript", () => {
  it("moves the catalog to TypeScript 7 and asks for pnpm install", async () => {
    await writeOldRoot();
    const result = createResult(".");
    await validateRootRules(tempDir, result, { fix: true });

    expect(await readFile(join(tempDir, "pnpm-workspace.yaml"), "utf-8")).toBe(
      oldWorkspace.replace("typescript: ^5.9.3", "typescript: ^7.0.2"),
    );
    expect(result.passes.some((p) => p.includes("TypeScript") && p.includes("pnpm install"))).toBe(true);
  });
});

describe("validateRootRules: second run", () => {
  it("finds nothing to fix", async () => {
    await writeOldRoot();
    await validateRootRules(tempDir, createResult("."), { fix: true });

    const second = createResult(".");
    await validateRootRules(tempDir, second, { fix: true });

    expect(autoFixes(second)).toEqual([]);
    expect(second.warnings).toEqual([]);
  });
});

describe("validateTsconfigBaseUrl", () => {
  it("removes a trailing baseUrl and keeps the JSON valid", async () => {
    const tsconfig = `{
  "extends": "./config/typescript/base.json",
  "compilerOptions": {
    "declaration": false,
    "baseUrl": "."
  }
}
`;
    await writeFile(join(tempDir, "tsconfig.json"), tsconfig);
    await validateTsconfigBaseUrl(tempDir, createResult("."), { fix: true });

    const text = await readFile(join(tempDir, "tsconfig.json"), "utf-8");
    expect(text).toBe(tsconfig.replace('"declaration": false,\n    "baseUrl": "."\n', '"declaration": false\n'));
    expect(() => JSON.parse(text)).not.toThrow();
  });

  it("removes a baseUrl in the middle of compilerOptions", async () => {
    const tsconfig = `{
  "compilerOptions": {
    "outDir": "dist",
    "baseUrl": ".",
    "types": ["vite/client"]
  }
}
`;
    await writeFile(join(tempDir, "tsconfig.json"), tsconfig);
    const result = createResult(".");
    await validateTsconfigBaseUrl(tempDir, result, { fix: true });

    expect(await readFile(join(tempDir, "tsconfig.json"), "utf-8")).toBe(
      tsconfig.replace('    "baseUrl": ".",\n', ""),
    );
    expect(autoFixes(result)).toHaveLength(1);

    const second = createResult(".");
    await validateTsconfigBaseUrl(tempDir, second, { fix: true });
    expect(autoFixes(second)).toEqual([]);
  });

  it("warns about a baseUrl other than the directory itself", async () => {
    const tsconfig = `{
  "compilerOptions": {
    "baseUrl": "src"
  }
}
`;
    await writeFile(join(tempDir, "tsconfig.json"), tsconfig);
    const result = createResult(".");
    await validateTsconfigBaseUrl(tempDir, result, { fix: true });

    expect(result.warnings.some((w) => w.includes("baseUrl"))).toBe(true);
    expect(await readFile(join(tempDir, "tsconfig.json"), "utf-8")).toBe(tsconfig);
  });

  it("warns instead of fixing when paths rely on baseUrl", async () => {
    const tsconfig = `{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] }
  }
}
`;
    await writeFile(join(tempDir, "tsconfig.json"), tsconfig);
    const result = createResult(".");
    await validateTsconfigBaseUrl(tempDir, result, { fix: true });

    expect(result.warnings.some((w) => w.includes("paths"))).toBe(true);
    expect(await readFile(join(tempDir, "tsconfig.json"), "utf-8")).toBe(tsconfig);
  });
});

describe("validateExpoTypescript", () => {
  const expoApp = `{
  "name": "@a/kiosk",
  "dependencies": {
    "expo": "^54.0.0"
  },
  "devDependencies": {
    "tailwindcss": "~3.4.17",
    "typescript": "catalog:"
  }
}
`;

  it("pins an Expo app that follows the catalog to the Expo TypeScript", async () => {
    await writeFile(join(tempDir, "package.json"), expoApp);
    const result = createResult("apps/kiosk");
    await validateExpoTypescript(tempDir, result, { fix: true });

    expect(await readFile(join(tempDir, "package.json"), "utf-8")).toBe(
      expoApp.replace('"typescript": "catalog:"', '"typescript": "~5.9.3"'),
    );
    expect(autoFixes(result)).toHaveLength(1);

    const second = createResult("apps/kiosk");
    await validateExpoTypescript(tempDir, second, { fix: true });
    expect(autoFixes(second)).toEqual([]);
  });

  it("pins an Expo app on TypeScript 7", async () => {
    await writeFile(join(tempDir, "package.json"), expoApp.replace("catalog:", "^7.0.2"));
    const result = createResult("apps/kiosk");
    await validateExpoTypescript(tempDir, result);

    expect(result.warnings.some((w) => w.includes("TypeScript"))).toBe(true);
  });

  it("leaves an app without expo alone", async () => {
    const web = expoApp.replace('"expo": "^54.0.0"', '"vite": "^8.0.0"');
    await writeFile(join(tempDir, "package.json"), web);
    const result = createResult("apps/web");
    await validateExpoTypescript(tempDir, result, { fix: true });

    expect(await readFile(join(tempDir, "package.json"), "utf-8")).toBe(web);
    expect(result.warnings).toEqual([]);
  });
});
