/**
 * Color token sheet mirroring the web theme (@simplix-react/ui theme/base.css
 * and theme/presets/*.css) with the SAME token names, converted from oklch to
 * hex for the React Native style engine. Values are injected as CSS variables
 * via NativeWind `vars()` by {@link SimplixThemeProvider}; components consume
 * them only through Tailwind utilities mapped in the package tailwind preset
 * (e.g. `bg-background`, `text-foreground`, `border-border`).
 */

/** A flat map of CSS variable name to color value (hex / hex8 / var reference). */
export type ColorTokenMap = Record<string, string>;

/** Light/dark pair of color token maps. */
export interface ThemeTokenSheet {
  light: ColorTokenMap;
  dark: ColorTokenMap;
}

/** Color preset identifiers — mirrors the web `THEMES` manifest values. */
export type ThemePresetName = "default" | "blue" | "green" | "krds" | "orange" | "rose" | "violet";

/** Neutral base tokens (`default` preset). Dark overrides only re-declared tokens. */
export const BASE_TOKENS: ThemeTokenSheet = {
  light: {
  "--background": "#ffffff",
  "--card": "#ffffff",
  "--surface-2": "#f9fafb",
  "--surface-3": "#f2f5f7",
  "--popover": "#ffffff",
  "--foreground": "#020618",
  "--card-foreground": "#020618",
  "--popover-foreground": "#020618",
  "--secondary-foreground": "#0f172b",
  "--muted-foreground": "#62748e",
  "--muted-2": "#7f8fa7",
  "--border": "#e2e8f0",
  "--border-strong": "#d3dae2",
  "--input": "#e2e8f0",
  "--ring": "#90a1b9",
  "--primary": "#0f172b",
  "--primary-foreground": "#f8fafc",
  "--primary-hover": "#1d2842",
  "--primary-soft": "#ecf0f9",
  "--primary-soft-2": "#dfe5f1",
  "--secondary": "#f1f5f9",
  "--muted": "#f1f5f9",
  "--accent": "#f1f5f9",
  "--accent-foreground": "#0f172b",
  "--destructive": "#e7000b",
  "--destructive-foreground": "#f8fafc",
  "--danger-soft": "#ffe8e5",
  "--success": "#179765",
  "--success-soft": "#dbf6e7",
  "--warning": "#bb4b00",
  "--warn-soft": "#ffefcd",
  "--info": "#0071df",
  "--purple": "#7e4ed7",
  "--purple-soft": "#f5f1fe",
  "--purple-soft-2": "#e8dffc",
  "--sidebar": "#0f172b",
  "--sidebar-foreground": "#f8fafc",
  "--sidebar-primary": "#f8fafc",
  "--sidebar-primary-foreground": "#0f172b",
  "--sidebar-accent": "#1d293d",
  "--sidebar-accent-foreground": "#f8fafc",
  "--sidebar-border": "#ffffff1a",
  "--sidebar-ring": "#6a7282",
  "--brand-bg": "var(--primary)",
  "--brand-fg": "var(--primary-foreground)",
  "--hatch-stroke": "var(--foreground)",
  "--hover-bg": "#0000000a",
  "--hover-bg-strong": "#00000012",
  "--scroll-thumb": "#00000033",
  "--scroll-thumb-hover": "#0000005c",
  "--chart-1": "#f54900",
  "--chart-2": "#009689",
  "--chart-3": "#104e64",
  "--chart-4": "#ffb900",
  "--chart-5": "#fe9a00",
  "--shadow-card": "var(--shadow-1)",
  "--shadow-pop": "var(--shadow-3)",
  "--bg": "var(--background)",
  "--surface": "var(--card)",
  "--fg": "var(--foreground)",
  "--fg-soft": "var(--secondary-foreground)",
  "--hairline": "var(--border)",
  "--hairline-2": "var(--border-strong)",
  "--primary-strong": "var(--primary-hover)",
  "--warn": "var(--warning)",
  "--danger": "var(--destructive)",
},
  dark: {
  "--background": "#020618",
  "--card": "#020919",
  "--surface-2": "#0a1628",
  "--surface-3": "#162235",
  "--popover": "#0f172b",
  "--foreground": "#f8fafc",
  "--card-foreground": "#f8fafc",
  "--popover-foreground": "#f8fafc",
  "--secondary-foreground": "#f8fafc",
  "--muted-foreground": "#90a1b9",
  "--muted-2": "#6d7b8f",
  "--border": "#ffffff1a",
  "--border-strong": "#ffffff2e",
  "--input": "#ffffff26",
  "--ring": "#6a7282",
  "--primary": "#e2e8f0",
  "--primary-foreground": "#0f172b",
  "--primary-hover": "#c9d2de",
  "--primary-soft": "#e2e8f026",
  "--primary-soft-2": "#e2e8f047",
  "--secondary": "#1d293d",
  "--muted": "#1d293d",
  "--accent": "#1d293d",
  "--accent-foreground": "#f8fafc",
  "--destructive": "#ff6467",
  "--destructive-foreground": "#f8fafc",
  "--danger-soft": "#451816",
  "--success": "#37b880",
  "--success-soft": "#073724",
  "--warning": "#eb9b00",
  "--warn-soft": "#3b2b0d",
  "--info": "#40a9ff",
  "--purple": "#a689f1",
  "--purple-soft": "#422e62",
  "--purple-soft-2": "#371b5b",
  "--hover-bg": "#ffffff0d",
  "--hover-bg-strong": "#ffffff17",
  "--scroll-thumb": "#ffffff29",
  "--scroll-thumb-hover": "#ffffff4d",
  "--chart-1": "#1447e6",
  "--chart-2": "#00bc7d",
  "--chart-3": "#fe9a00",
  "--chart-4": "#ad46ff",
  "--chart-5": "#ff2056",
},
};

/** Per-preset token overrides layered on top of {@link BASE_TOKENS}. */
export const PRESET_TOKENS: Record<Exclude<ThemePresetName, "default">, ThemeTokenSheet> = {
  blue: {
    light: {
      "--primary": "#155dfc",
      "--primary-foreground": "#f8fafc",
      "--secondary": "#e6f1ff",
      "--secondary-foreground": "#0d1d37",
      "--muted": "#e8f1fe",
      "--muted-foreground": "#667488",
      "--accent": "#dfecfe",
      "--accent-foreground": "#0d1d37",
      "--border": "#dae4f2",
      "--input": "#dae4f2",
      "--ring": "#155dfc",
      "--chart-1": "#155dfc",
      "--chart-2": "#009689",
      "--chart-3": "#ff6900",
      "--chart-4": "#7c86ff",
      "--chart-5": "#ff2056",
      "--sidebar": "#0f172b",
      "--sidebar-foreground": "#f8fafc",
      "--sidebar-primary": "#f8fafc",
      "--sidebar-primary-foreground": "#0f172b",
      "--sidebar-accent": "#1d293d",
      "--sidebar-accent-foreground": "#f8fafc",
      "--sidebar-border": "#ffffff1a",
      "--sidebar-ring": "#6a7282",
    },
    dark: {
      "--background": "#010818",
      "--foreground": "#f8fafc",
      "--card": "#040c1b",
      "--card-foreground": "#f8fafc",
      "--popover": "#0a1628",
      "--popover-foreground": "#f8fafc",
      "--primary": "#2b7fff",
      "--primary-foreground": "#040a1b",
      "--border": "#ffffff1a",
      "--input": "#ffffff26",
      "--secondary": "#18273c",
      "--secondary-foreground": "#f4f7fb",
      "--muted": "#1a273a",
      "--muted-foreground": "#8290a5",
      "--accent": "#18273c",
      "--accent-foreground": "#f4f7fb",
      "--ring": "#2b7fff",
      "--chart-1": "#2b7fff",
      "--chart-2": "#00bc7d",
      "--chart-3": "#fe9a00",
      "--chart-4": "#51a2ff",
      "--chart-5": "#ff637e",
    },
  },
  green: {
    light: {
      "--primary": "#009966",
      "--primary-foreground": "#f9fbf9",
      "--secondary": "#e7f4ec",
      "--secondary-foreground": "#002517",
      "--muted": "#e8f3ec",
      "--muted-foreground": "#64786d",
      "--accent": "#e0f0e6",
      "--accent-foreground": "#002517",
      "--border": "#dbe7df",
      "--input": "#dbe7df",
      "--ring": "#009966",
      "--chart-1": "#009966",
      "--chart-2": "#155dfc",
      "--chart-3": "#ff6900",
      "--chart-4": "#3bb3a2",
      "--chart-5": "#8e51ff",
      "--sidebar": "#0f172b",
      "--sidebar-foreground": "#f8fafc",
      "--sidebar-primary": "#f8fafc",
      "--sidebar-primary-foreground": "#0f172b",
      "--sidebar-accent": "#1d293d",
      "--sidebar-accent-foreground": "#f8fafc",
      "--sidebar-border": "#ffffff1a",
      "--sidebar-ring": "#6a7282",
    },
    dark: {
      "--background": "#000c05",
      "--foreground": "#f8faf9",
      "--card": "#030f09",
      "--card-foreground": "#f8faf9",
      "--popover": "#091a11",
      "--popover-foreground": "#f8faf9",
      "--primary": "#00a96e",
      "--primary-foreground": "#010f07",
      "--border": "#ffffff1a",
      "--input": "#ffffff26",
      "--secondary": "#162b20",
      "--secondary-foreground": "#f4f8f5",
      "--muted": "#192b21",
      "--muted-foreground": "#819588",
      "--accent": "#162b20",
      "--accent-foreground": "#f4f8f5",
      "--ring": "#00a96e",
      "--chart-1": "#00a96e",
      "--chart-2": "#2b7fff",
      "--chart-3": "#fe9a00",
      "--chart-4": "#3dc17f",
      "--chart-5": "#a684ff",
    },
  },
  krds: {
    light: {
      "--background": "#f2f3f5",
      "--card": "#ffffff",
      "--surface-2": "#f4f6f8",
      "--surface-3": "#ebeef2",
      "--popover": "#ffffff",
      "--foreground": "#15171c",
      "--card-foreground": "#15171c",
      "--popover-foreground": "#15171c",
      "--secondary-foreground": "#2d3038",
      "--muted-foreground": "#5c6370",
      "--muted-2": "#8990a0",
      "--border": "#eceef1",
      "--border-strong": "#dde0e6",
      "--input": "#eceef1",
      "--ring": "#246bfd",
      "--primary": "#246bfd",
      "--primary-foreground": "#ffffff",
      "--primary-hover": "#0f54e0",
      "--primary-soft": "#e4edff",
      "--primary-soft-2": "#d6e2ff",
      "--secondary": "#f4f6f8",
      "--muted": "#f4f6f8",
      "--accent": "#f4f6f8",
      "--accent-foreground": "#15171c",
      "--success": "#159e5c",
      "--success-soft": "#e2f5eb",
      "--warning": "#c97a00",
      "--warn-soft": "#fff3de",
      "--destructive": "#d4351f",
      "--destructive-foreground": "#ffffff",
      "--danger-soft": "#fdece8",
      "--purple": "#7c3aed",
      "--purple-soft": "#faf5ff",
      "--purple-soft-2": "#ede9fe",
      "--sidebar": "#f7f8fa",
      "--sidebar-foreground": "#2d3038",
      "--sidebar-primary": "#246bfd",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#ffffff",
      "--sidebar-accent-foreground": "#15171c",
      "--sidebar-border": "#eceef1",
      "--sidebar-ring": "#246bfd",
      "--brand-bg": "#246bfd",
      "--brand-fg": "#ffffff",
      "--hatch-stroke": "#15171c",
    },
    dark: {
      "--background": "#0b0d11",
      "--card": "#14171d",
      "--surface-2": "#1b1f27",
      "--surface-3": "#232a36",
      "--popover": "#14171d",
      "--foreground": "#e8eaee",
      "--card-foreground": "#e8eaee",
      "--popover-foreground": "#e8eaee",
      "--secondary-foreground": "#c9cdd4",
      "--muted-foreground": "#8e96a4",
      "--muted-2": "#6a7180",
      "--border": "#242935",
      "--border-strong": "#2f3540",
      "--input": "#242935",
      "--ring": "#6195ff",
      "--primary": "#6195ff",
      "--primary-foreground": "#ffffff",
      "--primary-hover": "#80a8ff",
      "--primary-soft": "#6195ff24",
      "--primary-soft-2": "#6195ff47",
      "--secondary": "#1b1f27",
      "--muted": "#1b1f27",
      "--accent": "#1b1f27",
      "--accent-foreground": "#e8eaee",
      "--success": "#2ab76c",
      "--success-soft": "#143628",
      "--warning": "#dba042",
      "--warn-soft": "#3a2b0f",
      "--destructive": "#f26e5c",
      "--destructive-foreground": "#ffffff",
      "--danger-soft": "#3a1a14",
      "--purple": "#a78bfa",
      "--purple-soft": "#4c1d95",
      "--purple-soft-2": "#3b0764",
      "--sidebar": "#14171d",
      "--sidebar-foreground": "#c9cdd4",
      "--sidebar-primary": "#6195ff",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-accent": "#1f242e",
      "--sidebar-accent-foreground": "#e8eaee",
      "--sidebar-border": "#242935",
      "--sidebar-ring": "#6195ff",
      "--brand-bg": "#6195ff",
      "--brand-fg": "#0b0d11",
      "--hatch-stroke": "#ffffff",
    },
  },
  orange: {
    light: {
      "--primary": "#e17100",
      "--primary-foreground": "#fcfaf8",
      "--secondary": "#fbede3",
      "--secondary-foreground": "#341a07",
      "--muted": "#f9eee6",
      "--muted-foreground": "#816f62",
      "--accent": "#f8e8dc",
      "--accent-foreground": "#341a07",
      "--border": "#ede1d8",
      "--input": "#ede1d8",
      "--ring": "#e17100",
      "--chart-1": "#e17100",
      "--chart-2": "#155dfc",
      "--chart-3": "#009966",
      "--chart-4": "#fcb84e",
      "--chart-5": "#8e51ff",
      "--sidebar": "#0f172b",
      "--sidebar-foreground": "#f8fafc",
      "--sidebar-primary": "#f8fafc",
      "--sidebar-primary-foreground": "#0f172b",
      "--sidebar-accent": "#1d293d",
      "--sidebar-accent-foreground": "#f8fafc",
      "--sidebar-border": "#ffffff1a",
      "--sidebar-ring": "#6a7282",
    },
    dark: {
      "--background": "#100602",
      "--foreground": "#fbf9f8",
      "--card": "#130a05",
      "--card-foreground": "#fbf9f8",
      "--popover": "#1f130b",
      "--popover-foreground": "#fbf9f8",
      "--primary": "#fb9a17",
      "--primary-foreground": "#130803",
      "--border": "#ffffff1a",
      "--input": "#ffffff26",
      "--secondary": "#322218",
      "--secondary-foreground": "#f9f6f3",
      "--muted": "#30231a",
      "--muted-foreground": "#9b8c81",
      "--accent": "#322218",
      "--accent-foreground": "#f9f6f3",
      "--ring": "#fb9a17",
      "--chart-1": "#fb9a17",
      "--chart-2": "#2b7fff",
      "--chart-3": "#00a96e",
      "--chart-4": "#fad18a",
      "--chart-5": "#a684ff",
    },
  },
  rose: {
    light: {
      "--primary": "#ff2056",
      "--primary-foreground": "#fcf9f9",
      "--secondary": "#faeced",
      "--secondary-foreground": "#361719",
      "--muted": "#f8edee",
      "--muted-foreground": "#846c6d",
      "--accent": "#f8e6e7",
      "--accent-foreground": "#361719",
      "--border": "#ece0e1",
      "--input": "#ece0e1",
      "--ring": "#ff2056",
      "--chart-1": "#ff2056",
      "--chart-2": "#155dfc",
      "--chart-3": "#009966",
      "--chart-4": "#ffa1ad",
      "--chart-5": "#ff6900",
      "--sidebar": "#0f172b",
      "--sidebar-foreground": "#f8fafc",
      "--sidebar-primary": "#f8fafc",
      "--sidebar-primary-foreground": "#0f172b",
      "--sidebar-accent": "#1d293d",
      "--sidebar-accent-foreground": "#f8fafc",
      "--sidebar-border": "#ffffff1a",
      "--sidebar-ring": "#6a7282",
    },
    dark: {
      "--background": "#110505",
      "--foreground": "#fcf9f9",
      "--card": "#140909",
      "--card-foreground": "#fcf9f9",
      "--popover": "#201112",
      "--popover-foreground": "#fcf9f9",
      "--primary": "#ff637e",
      "--primary-foreground": "#140708",
      "--border": "#ffffff1a",
      "--input": "#ffffff26",
      "--secondary": "#332021",
      "--secondary-foreground": "#faf5f6",
      "--muted": "#312122",
      "--muted-foreground": "#9e898a",
      "--accent": "#332021",
      "--accent-foreground": "#faf5f6",
      "--ring": "#ff637e",
      "--chart-1": "#ff637e",
      "--chart-2": "#2b7fff",
      "--chart-3": "#00a96e",
      "--chart-4": "#fcc8cf",
      "--chart-5": "#fe9a00",
    },
  },
  violet: {
    light: {
      "--primary": "#8e51ff",
      "--primary-foreground": "#fafafc",
      "--secondary": "#f0eefd",
      "--secondary-foreground": "#221d37",
      "--muted": "#f0eefa",
      "--muted-foreground": "#737083",
      "--accent": "#ebe9fa",
      "--accent-foreground": "#221d37",
      "--border": "#e3e1ef",
      "--input": "#e3e1ef",
      "--ring": "#8e51ff",
      "--chart-1": "#8e51ff",
      "--chart-2": "#ff2056",
      "--chart-3": "#009689",
      "--chart-4": "#c1abff",
      "--chart-5": "#ff6900",
      "--sidebar": "#0f172b",
      "--sidebar-foreground": "#f8fafc",
      "--sidebar-primary": "#f8fafc",
      "--sidebar-primary-foreground": "#0f172b",
      "--sidebar-accent": "#1d293d",
      "--sidebar-accent-foreground": "#f8fafc",
      "--sidebar-border": "#ffffff1a",
      "--sidebar-ring": "#6a7282",
    },
    dark: {
      "--background": "#090515",
      "--foreground": "#faf9fc",
      "--card": "#0d0a18",
      "--card-foreground": "#faf9fc",
      "--popover": "#171324",
      "--popover-foreground": "#faf9fc",
      "--primary": "#a684ff",
      "--primary-foreground": "#0b0917",
      "--border": "#ffffff1a",
      "--input": "#ffffff26",
      "--secondary": "#262336",
      "--secondary-foreground": "#f7f6fa",
      "--muted": "#262434",
      "--muted-foreground": "#8f8d9e",
      "--accent": "#262336",
      "--accent-foreground": "#f7f6fa",
      "--ring": "#a684ff",
      "--chart-1": "#a684ff",
      "--chart-2": "#ff637e",
      "--chart-3": "#00bc7d",
      "--chart-4": "#d6cdfc",
      "--chart-5": "#fe9a00",
    },
  },
};

/**
 * Resolve the effective color token map for a preset and scheme.
 *
 * Mirrors the web CSS cascade: base light, then `.dark` overrides, then the
 * preset's light block, then the preset's dark block. `var(--x)` references
 * (e.g. `--brand-bg: var(--primary)`) are resolved after merging so preset
 * primaries flow into dependent tokens.
 */
export function resolveThemeTokens(
  preset: ThemePresetName,
  scheme: "light" | "dark",
): ColorTokenMap {
  const merged: ColorTokenMap = { ...BASE_TOKENS.light };
  if (scheme === "dark") Object.assign(merged, BASE_TOKENS.dark);
  if (preset !== "default") {
    const presetSheet = PRESET_TOKENS[preset];
    Object.assign(merged, presetSheet.light);
    if (scheme === "dark") Object.assign(merged, presetSheet.dark);
  }
  // Resolve var() references (bounded — reference chains are at most a few deep).
  for (let pass = 0; pass < 4; pass++) {
    let changed = false;
    for (const [key, value] of Object.entries(merged)) {
      const ref = value.match(/^var\((--[a-z0-9-]+)\)$/);
      if (ref) {
        const target = merged[ref[1]];
        if (target !== undefined && target !== value) {
          merged[key] = target;
          changed = true;
        }
      }
    }
    if (!changed) break;
  }
  return merged;
}
